FROM golang:1.24-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
COPY gen/ ./gen/
COPY FlightService/ ./FlightService/

RUN go mod download
RUN go build -o flight-service ./FlightService

FROM alpine
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/flight-service .
EXPOSE 8080
CMD ["./flight-service", "-port", "8080"]