services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway
    depends_on:
      postgres:
        condition: service_healthy
    command: -url=jdbc:postgresql://postgres:5432/marketplace -user=postgres -password=postgres -locations=filesystem:/flyway/sql -connectRetries=10 migrate
    volumes:
      - ./db/migrations:/flyway/sql
