FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /out/consumer ./cmd/consumer

FROM alpine:3.19
RUN apk add --no-cache ca-certificates tzdata
COPY --from=build /out/consumer /app/consumer
WORKDIR /app
EXPOSE 9080
ENTRYPOINT ["/app/consumer"]
