apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse_ds
    isDefault: true
    jsonData:
      server: clickhouse
      port: 8123
      username: default
      protocol: http
      defaultDatabase: default
    secureJsonData:
      password: ""
    version: 1
    editable: true
